[mysql_servers]
# incase of Ec2 you have Private key
# rockey-vm ansible_host=192.168.12.105 ansible_user=nosudopasswd ansible_ssh_private_key_file=~/.ssh/rockey-vm.pem

ubuntu-server-vm ansible_host=192.168.13.10 ansible_user=ali  
