---
# tasks file for ansible-mysql-prod

- name: Install MySql Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: install Mysql Server
  yum:
    name: mariadb-server
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat" 

- name: Ensure Mysql Running
  service:
    name: mysql
    state: started
    enabled: yes
  when: ansible_os_family == "Debian"

- name: Ensure MySQL Running Rocky
  service:
    name: mariadb
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Install pymysql dependencies
  apt:
    name: python3-pymysql
    state: present
  when: ansible_os_family == "Debian"

- name: install pymysql dependencies
  yum:
    name: python3-PyMySQL
    state: present
  when: ansible_os_family == "RedHat"

- name: Set root user password & authentication plugin
  mysql_user:
    name: root
    host: localhost
    password: "{{mysql_root_password}}"
    login_user: root
    login_password: "{{mysql_root_password}}"
    check_implicit_admin: yes
  
- name: Remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Disallow Remote root login
  mysql_user:
    name: root
    host: "%"
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Flush Privileges
  mysql_query:
    query: FLUSH PRIVILEGES
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Create Application Database
  mysql_db:
    name: "{{my_app_database}}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Create Application user
  mysql_user:
    name: "{{my_app_user}}"
    password: "{{my_app_user_password}}"
    priv: "{{my_app_database}}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Configure MySql
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: Restart MySql
