---
# tasks file for ansible-mysql-prod

- name: Install MySql Server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure Mysql Running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Install pymysql dependencies
  apt:
    name: python3-pymysql
    state: present
    

- name: Set root user password & authentication plugin
  mysql_user:
    name: root
    host: localhost
    password: "{{mysql_root_password}}"
    plugin: mysql_native_password
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove anonymous user
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Disallow Remote root login
  mysql_user:
    name: root
    host: "%"
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Remove test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Flush Privileges
  mysql_query:
    name: FLUSH PRIVILEGES
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Create Application Database
  mysql_db:
    name: "{{my_app_database}}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Create Application user
  mysql_user:
    name: "{{my_app_user}}"
    password: "{{my_app_user_password}}"
    priv: "{{my_app_database}}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{mysql_root_password}}"

- name: Configure MySql
  template:
    src: mysqld.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: Restart MySql
